# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4250c3b2c887efa1bdc41cef22137e4782e9dbecae2e25af3eefc495824a739d13efa8096095134e6cd6ecc2cece9da654716c21ab13c4dbdb32ffce077c60d1

test:
  secret_key_base: c82f8cf783799ae2159841a419804e5f25c26a27c918edf605aee4a52edd802fcd53c4feff2163ce68408b9d3b9ffe54df0435c40ab83b9894cc140ba6b08fcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
